### ISSUE TITLE
Connot connect to auction repository address

### ISSUE THREAD

**Issue by morangeous** [iNDicat0r/mastering-ethereum-auction-dapp#3]
Hi bro.
I am really thankful to your contribution to this great project. However, I am confused about why I cannot connect to the auction repository address: http://52.59.238.144:8545
Any help will be appreciate!
Looking forward to your reply

**Comment by iNDicat0r** [comment]
Hi
I was running this node for demo purposes. You could easily setup your own dev node and deploy the contracts!

**Comment by morangeous** [comment]
OK, really thanks to your help
